# Generated by Django 4.2.16 on 2025-11-18 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('media_type', models.CharField(choices=[('photo', 'Фото'), ('animation', 'GIF'), ('video', 'Видео')], max_length=20, verbose_name='Тип медиа')),
                ('media_file', models.FileField(upload_to='media_content/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Медиа контент',
                'verbose_name_plural': 'Медиа контент',
            },
        ),
        migrations.CreateModel(
            name='TextTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаблон текста',
                'verbose_name_plural': 'Шаблоны текстов',
            },
        ),
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateField(unique=True, verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=255, verbose_name='Название поста')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('published', 'Опубликован'), ('failed', 'Ошибка')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Время публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('media_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.mediacontent', verbose_name='Медиа')),
                ('text_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.texttemplate', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Telegram пост',
                'verbose_name_plural': 'Telegram посты',
                'ordering': ['post_date'],
            },
        ),
    ]
