# Generated by Django 4.2.16 on 2025-11-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('department', models.CharField(max_length=255, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('date_birthday', models.DateField(verbose_name='Дата рождения')),
                ('import_date', models.DateField(auto_now_add=True, verbose_name='Дата импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Именинник',
                'verbose_name_plural': 'Именинники',
                'indexes': [models.Index(fields=['date_birthday'], name='post_birthd_date_bi_a615f1_idx'), models.Index(fields=['import_date'], name='post_birthd_import__73388f_idx')],
            },
        ),
    ]
