# Generated by Django 4.2.16 on 2025-11-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_birthdayperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampost',
            name='final_text',
            field=models.TextField(blank=True, verbose_name='Финальный текст'),
        ),
    ]
