# Generated by Django 4.2.16 on 2025-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_telegrampost_final_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampost',
            name='people_count',
            field=models.IntegerField(default=0, verbose_name='Количество именинников'),
        ),
    ]
