# Generated by Django 4.2.16 on 2025-11-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webfacetg', '0001_initial'),
    ]

    operations = [
    ]
